# Generated by Django 2.2.4 on 2019-08-17 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
